spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_store?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #templates访问静态资源配置
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    mode: HTML


server:
  port: 8083
#分页配置
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

file:
  upload:
    path: \src\main\resources\static\images\
    path.relative: /images/**
